name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  libraryVersion: '1.0.1'

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Package button
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-button-library-${{ env.libraryVersion }}
          path: libraries/button/
      
      - name: Package buzzer
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-buzzer-library-${{ env.libraryVersion }}
          path: libraries/buzzer/

      - name: Package display
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-display-library-${{ env.libraryVersion }}
          path: libraries/display/
      
      - name: Package interrupt
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-interrupt-library-${{ env.libraryVersion }}
          path: libraries/interrupt/
      
      - name: Package led
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-led-library-${{ env.libraryVersion }}
          path: libraries/LED/
      
      - name: Package timer
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-timer-library-${{ env.libraryVersion }}
          path: libraries/timer/
      
      - name: Package uart
        uses: actions/upload-artifact@v4
        with:
          name: m12864stk-uart-library-${{ env.libraryVersion }}
          path: libraries/UART/

      - name: Create board manager
        run: |
          mkdir -p ${{ env.libraryVersion }}
          cp -r cores ${{ env.libraryVersion }}/
          cp -r libraries ${{ env.libraryVersion }}/
          cp boards.txt ${{ env.libraryVersion }}/
          cp LICENSE ${{ env.libraryVersion }}/
          cp platform.txt ${{ env.libraryVersion }}/
          cp programmers.txt ${{ env.libraryVersion }}/
          cp README.md ${{ env.libraryVersion }}/
          zip -r m12864stk-${{ env.libraryVersion }}.zip ${{ env.libraryVersion }}
        
      - name: Print details
        run: |
          echo "# m12864stk-${{ env.libraryVersion }}.zip" >> $GITHUB_STEP_SUMMARY
          echo "SHA256: $(sha256sum m12864stk-${{ env.libraryVersion }}.zip)" >> $GITHUB_STEP_SUMMARY
          echo "Size: $(ls -l m12864stk-${{ env.libraryVersion }}.zip | cut -d' ' -f5)" >> $GITHUB_STEP_SUMMARY

      - name: Package board manager
        uses: actions/upload-artifact@v4
        id: package-board-manager
        with:
          name: m12864stk-${{ env.libraryVersion }}
          path: m12864stk-${{ env.libraryVersion }}.zip
